### ISSUE TITLE
permission 

### ISSUE THREAD

**Issue by Shinryua** [Resxt/Plutonium-T6-Scripts#3]
hi im not a expert witch script how i put permission one person level 4?

**Comment by Resxt** [comment]
Already answered on the [forum](https://forum.plutonium.pw/topic/32214/permission-resxt)

For a server paste the dvars from the [configuration section](https://github.com/Resxt/Plutonium-T6-Scripts/tree/main/chat_commands#configuration) in your server's CFG.
You can edit the dvar values by reading the [dvars section](https://github.com/Resxt/Plutonium-T6-Scripts/tree/main/chat_commands#dvars)
